// 由「源码抽取」生成：每个模组「可修改的键名」清单。
// 只写源码里真实出现的键名，**不编造**；中文说明优先取源码里的中文注释，取不到就留空字符串。
var MODKEYS = {
  doupo: [
    ['doupo_life_art_attr', '斗气属性镜像（面板可见；0..5，-1 表示尚未习得功法）', ''],
    ['doupo_life_dodge', '闪避率%（斗王·化翼机动；受击概率免伤）', ''],
    ['doupo_life_slow', '空间压制%（斗宗；命中概率上减速/封锁状态）', ''],
    ['doupo_life_defense', '防御（斗气护体；受击减伤=def/(def+300)）', ''],
    ['doupo_life_penetration', '空间穿透%（斗尊·撕裂空间；无视敌方防御比例）', ''],
    ['doupo_life_lifesteal', '生命汲取%（斗皇·能量掠夺；伤害回血）', ''],
    ['doupo_life_resistance', '领域威压%（斗圣；受击额外减伤）', ''],
    ['doupo_life_realm', '境界数值镜像（面板可见）', ''],
    ['doupo_life_fire', '异火数镜像（M2 启用）', ''],
    ['doupo_life_synergy', 'v0.35.50 属性×异火协同档位（面板可见）', ''],
    ['doupo_life_poison', '毒力（厄难毒体线，M2/M4 启用）', ''],
    ['doupo_life_talent', '斗气修炼天赋档镜像（1..5，v0.4.4）', ''],
    ['doupo_life_soul', '灵魂大境镜像（0=凡境..3=帝境，v0.4.5）', ''],
    ['doupo_life_soul_talent', '灵魂天赋档镜像（1..3，v0.4.5）', ''],
    ['doupo_life_talent_speed', 'v0.4.8 修炼速度可见化', ''],
    ['doupo_life_clan_purity', 'v0.6.38 古族血脉纯度镜像', ''],
    ['doupo_life_lineage_level', 'v0.27.50 修士血脉等级镜像（0..4）', ''],
    ['doupo_life_beast_tier', 'v0.7.0 妖兽阶镜像', ''],
    ['doupo_life_beast_star', 'v0.10.0 魔兽星镜像（阶内 1..9）', ''],
    ['doupo_life_beast_bloodline', 'v0.10.0 魔兽血脉镜像', ''],
    ['doupo_life_manasteal', '斗气汲取%（斗皇·能量掠夺；伤害回蓝）', ''],
    ['doupo_life_block', '格挡率%（受击概率触发大幅减伤）', ''],
    ['doupo_life_break', '破击率%（削对方格挡率，攻方侧）', ''],
    ['doupo_life_tenacity', '韧性%（概率抵抗控制/减速）', ''],
    ['doupo_life_counter', 'v0.6.26 纳戒护体（装备专属减伤）', ''],
    ['doupo_life_rule', '本源法则（斗帝：1=免疫控制/无视闪避威压）', ''],
    ['chinese_family_name', '「全文明种族版中文名」写入 actor.data 的「姓」键（跨 mod 只读，检测始祖姓氏用）', ''],
    ['phenotype_skin_skin_medium', '远古人类统一「古铜」肤色（复用原版 skin_medium 表型做族徽，不改数值）', ''],
    ['doupo_life_slow_debuff', '空间迟滞：speed -80', ''],
    ['doupo_life_paralyze', '空间封锁：speed -250（近定身）', ''],
    ['burning', '灼烧（原版状态；金帝焚天炎命中附加）', ''],
    ['inspired', '原版状态 id：**鼓舞**（`StatusLibrary` 已注册，dur=60：`multiplier_speed`/`multiplier_crit`/`multiplier_attack_speed` 各 +0.3）', ''],
    ['confused', '原版状态 id：**混乱**（`StatusLibrary` 已注册，dur=10，`affects_mind`）', ''],
    ['doupo_life_wya_pressure', '威压减速状态的 asset id（在 `DoupoLifeAssets.RegisterCombatStatuses` 注册）', ''],
    ['doupo_life.alchemist.pdi', '帝品炼药师的 trait id（v0.19.23 起品阶数值由 10 变 12，此 id 刻意保持不变以兼容旧档）', ''],
    ['fx_explosion_huge', '原版沙皇炸弹用的那个特效 asset（Cecil 实证）', ''],
    ['doupo_life.art.burst', '秘法爆发到期（世界秒）', ''],
    ['doupo_life.gold', 'int：金币', ''],
    ['doupo_life.trade_cd', 'float：上次寄售时间（世界秒）', ''],
    ['doupo_life.buy_cd', 'float：上次竞买时间（世界秒）', ''],
  ],
  guigu: [
    ['Xiuxian_Human', '修仙人族贴图/普通建筑组 architecture id：Xiuxian_Human（帐篷小屋风）', ''],
    ['xiuxian_standalone_succession_realm_qiyun', '历史 id：原「道统尊卑」文化继位特质（已停用；仍用于从物种默认列表清理旧条目）', ''],
    ['lq_td_wanjie_jianxin', '仙道《吐纳术》/《太元引气篇》练气词条 id（抽取自练气词条库）', ''],
    ['xiuxian_standalone_spawn_chiwen', '螭吻生成神力名称键（无点号，对应 _description 说明）', ''],
    ['xiuxian_standalone_civ_chiwen', '螭吻文明王国模板（独立于原版 miniciv_piranha，避免与人族阵营混用）', ''],
    ['xiuxian_standalone_wild_chiwen', '螭吻荒野王国模板（投放到地图前的默认阵营）', ''],
    ['xiuxian_standalone_hun_dun_shenlei', '混沌神力名称 locale（_description 为说明）', ''],
    ['Xiuxian_Human_Ge', '修仙人族特殊建筑组（阁楼风）architecture id', ''],
    ['xiuxian.standalone.abyssal_treasure_land_curse', '深海馈赠/诅咒：上岸虚弱状态', ''],
    ['world_power_melee_drain', '双方皆有天地之力时，攻击方单次命中削减总量（上限×比例 + wd + 武道陆地神仙 +6）。普通 5%；仙道登仙中期起 20%', ''],
    ['world_power_max_wanliu_snap', '与 KeyWorldPowerMax 同批写入，用于万流归风等临时上限变更时自动失效', ''],
    ['world_power_max_happiness_snap', '与 KeyWorldPowerMaxWanliuBonusSnap 同批写入；幸福度变更时须失效天地之力上限缓存', ''],
    ['cfe_gongfa_entry_mult', '功法词条等带来的修炼倍率加成缓存键（与 CultivationData.GetGongfaEntryCultivationMultiplierBonus 对应）', ''],
    ['cfe_acquired_luck_mult', '后天气运带来的修炼倍率加成缓存键', ''],
    ['xiuxian.standalone.aojiao_xiaohuo_qilin_cd', '傲娇小火麒麟：上次开启伴战的世界时间', ''],
    ['xiuxian.standalone.aojiao_xiaohuo_qilin_active_until', '傲娇小火麒麟：伴战结束世界时间', ''],
    ['red_orb', '原版邪恶法杖弹体（evil_staff.projectile）', ''],
    ['lq_sp_hp', '练气特殊词条「归元生气」：先天气运生命倍率→修炼倍率', ''],
    ['xiuxian.standalone.cangsheng', '神通·苍生回元（神通栏，木属性）', ''],
    ['xiuxian.standalone.cangsheng_cd_last', '神通·苍生回元上次释放时间（UnityEngine.Time.time）', ''],
    ['xiuxian.standalone.cangsheng_slow', '神通·苍生回元：超强减速状态', ''],
    ['cloud_fire', '本体火焰云（地狱之云）资�?id�?/summary>', ''],
    ['xiuxian.standalone.chiyan', '神通·赤焰焚原（神通栏，火属性）', ''],
    ['xiuxian.standalone.chiyan_cd_last', '神通·赤焰焚原上次释放时间（UnityEngine.Time.time）', ''],
    ['xiuxian.standalone.acquired_kaidaozhe', '后天气运「开道者」在 locale 中的键；部分环境可能写入本键而非「开道者(红)」', ''],
    ['xiuxian.standalone.acquired_chuanyuezhe', '后天气运「穿越者」在 locale 中的键；部分存档/工具可能写入本键而非中文名', ''],
    ['xiuxian.standalone.z_z_z_dimai_zhaohuan', '土系绝技·地脉召唤（由地脉精粹授予）', ''],
    ['had_nightmare', '本体「做过噩梦」之后天气运状态（与睡眠可分时存在）', ''],
    ['fx_slash', '默认使用的底座特效 ID，带 SpriteAnimation 组件', ''],
    ['xiuxian.standalone.gangfeng', '神通·罡风摄元（神通栏，风属性）', ''],
    ['xiuxian.standalone.gangfeng_cd_last', '神通·罡风摄元上次释放时间（UnityEngine.Time.time）', ''],
    ['xiuxian.standalone.heaven_earth_calamity_madness', '天地大劫·劫煞失心（临时疯狂 120 秒）', ''],
    ['proj_WuxianFeather', '仙羽·剑域灵羽投射物 id，仅仙羽效果使用；灵技庚金剑诀使用 LingjiProjectiles.ProjIdJinjianShu，二者不同资产', ''],
    ['proj_JueyingSword_normar', '与灵技·庚金剑诀 / 金剑术相同贴图', ''],
    ['xiuxian.standalone.jinfeng', '神通·金锋裂穹（神通栏，金/剑属性）', ''],
    ['xiuxian.standalone.jinfeng_cd_last', '神通·金锋裂穹上次释放时间（UnityEngine.Time.time）', ''],
    ['xiuxian.standalone.S1_jinfeng_gold_blade', '神通专用金刃投射物（另 1 号）', ''],
    ['xiuxian.standalone.A_jinyao_jianyin', '金曜剑吟绝技专属投射物 id（A 段）', ''],
    ['xiuxian.standalone.B_liujin_jianying', '鎏金剑影绝技专属投射物 id（B 段）', ''],
    ['xiuxian.standalone.C_longzhen_left', '龙镇八荒绝技：目标在施法者左侧时使用', ''],
  ],
  tianren: [
    ['xiuxian.standalone.martial_innate_luck', '鬼谷并行存档：武道先天气运键（用于迁移到本模组）', ''],
    ['God_Vault', '单位面板左侧「神藏」页签入口图标（不含 .png）', ''],
    ['God_Vault_1', '神藏染色体贴图：按解锁顺序 1→2→3（后天初/中/后期各开一条）', ''],
    ['tianren.martial.hun_dun_shenlei_godpower', '混沌神雷神力 id（笔刷抹杀，独立于鬼谷）', ''],
    ['tianren.martial.cultivation_realm_level', '修炼修为等级 0~16（五境各三小境 + 陆地神仙）', '0~16'],
    ['tianren.martial.cultivation_level_scheme', '修为等级方案：1=现行 0~16；缺省时需判定是否旧 0~9', '0~16'],
    ['tianren.martial.martial_realm_level', '境界特质序号 1~6，由修为等级同步', '1~6'],
    ['tianren.martial.gongfa_type', '功法类型：sword / spear / finger / fist / blade / array', ''],
    ['tianren.martial.gongfa_rename_used', '《归元决》突破后天后是否已改名并抽取类型', ''],
    ['tianren.martial.gongfa_xiantian_skill', '先天功法剑招 id，目前 jianqi。旧档曾写在 DataKeyGongfaHoutianSkill', ''],
    ['tianren.martial.gongfa_houtian_skill', '旧键：后天剑招。仅作存档迁移读取', ''],
    ['tianren.martial.gongfa_zongshi_sword_skill', '剑系宗师招：到达宗师时抽取一次，剑落银河或归一剑决', ''],
    ['tianren.martial.zongshi_shenfa', '宗师身法：到达宗师抽取一次，切换功法类型时重随', ''],
    ['tianren.martial.shenzang', '后天神藏：三染色体隐窍序列（每人独立）。格式见 MartialShenZangData', ''],
    ['tianren.martial.shenzang_unlocked', '已解锁神藏 id 列表，逗号分隔（后天初=躯骸、中=生机、后=灵府，固定顺序）', ''],
    ['tianren.martial.shenzang_synergy_v2', '神藏隐窍序列布局版本（5=位阶随机；6=杂乱隐窍；7=固定解锁顺序）', ''],
    ['tianren.martial.shenzang_exp_fill_touched', '已走空隐窍+经验填点（开辟留空或成功填过一格）；v8 迁移勿清空其进度', ''],
    ['tianren.martial.shenzang_locus_fill_bar', '后天填下一格的隐藏进度（0~当前小境单格消耗，不进面板）', ''],
    ['tianren.martial.tuofan_gilded_count', '蜕凡：已镀金普通隐窍数量（先天及以上视为金满，可不写此键）', ''],
    ['tianren.martial.tuofan_entered', '已突破进入蜕凡小境（0/1；缺省由镀金进度/修为推断）', ''],
    ['tianren.martial.heyi_entered', '已突破进入合道小境（0/1；缺省由修为推断）', ''],
    ['tianren.martial.temp_current_health', 'updateStats 入口暂存当前生命（合并后按比例抬升，避免卡在特质上限）', ''],
    ['tianren.martial.neili_regen_acc', '内力自然回复小数累计，避免每秒至少回 1 点把承伤打穿', ''],
    ['tianren.martial.neili_combat_spend_pending', '战斗刚扣过内力：1=下次 updateStats 回写勿高于实况（防高倍速快照回滚）', ''],
    ['tianren.martial.dao_heart', '道心天骄：单一特质，档位存 DataKeyDaoHeartTier', ''],
    ['tianren.martial.combat_art_spell_boost', '意入式真元增幅：真元百分比，不用原版 spell_boost 固定 +100', ''],
    ['tianren.martial.combat_art_motivated', '意入式激励：攻速 +6（高于原版 motivated 的 +2）', ''],
    ['tianren.martial.combat_skill_zongshi_dacheng', '宗师中/后强制把技巧提到大成的次数', '0～2'],
    ['tianren.martial.combat_art_skill_mask', '意入式已解锁技巧位掩码（突破宗师初/中/后判定写入；战斗只读此键）', ''],
    ['tianren.martial.will_skill_infusion_mask', '大宗师：技巧融入位掩码（5 bit，对应 dash/block/dodge/backstep/deflect）', ''],
    ['tianren.martial.will_skill_infusion_packed', '大宗师：融入效果打包（每技巧 8bit×5；含效果种类/融入时档位/入意标记）', ''],
    ['tianren.martial.will_skill_infusion_gates', '大宗师：已判定融入的闸门 bit0=初 bit1=中 bit2=后', ''],
    ['tianren.martial.will_domain_shred_factor', '领域压制强度（施法者融入写入目标，ApplyEnemyStatShred 读取）', ''],
    ['tianren.martial.combat_art_next_hit_burst_mul', '意入式：下一击额外爆发倍率（叠在冲刺下一击之上）', ''],
    ['tianren.martial.combat_art_next_hit_execute_hp', '意入式：下一击若目标气血比例低于此值则处决', ''],
    ['tianren.martial.combat_art_next_hit_hp_pct', '意入式：下一击追加目标当前气血百分比伤害（不砍上限）', ''],
    ['tianren.martial.combat_art_lock_hp_until', '意入式短时锁血截止（getCurWorldTime）', ''],
    ['tianren.martial.combat_art_madness_owned', '意入式临时疯狂：1=本模组挂上的，到期可摘', ''],
    ['tianren.martial.aspect_cap_fill_pending', '显化刚展开：下一次 updateStats 把当前生命/真元/内力按上限倍率补一次', ''],
    ['tianren.martial.neili_array_cur_boost', '内力法阵已把当前内力乘过 1.4，结束时要除回去', ''],
  ],
  xuanjian: [
    ['xuanjian.vnext.yuanzhao.credential.state', '0无 1持函 2游历中 3已结算 4辞却/失效', ''],
    ['xuanjian.vnext.fuqi.sense_result', '0=未判定 1=成功 2=失败', ''],
    ['xuanjian.vnext.zijin_sword.research.decision', '0=未判定 1=主动投入 2=放弃', ''],
    ['xuanjian.vnext.weapon_art.intent_lock_reason', '1=紫府前未悟，2=器意尝试耗尽', ''],
    ['source_rules_missing', '旧档兼容', ''],
    ['manual_record_ready', '旧档兼容', ''],
    ['Ready', '', ''],
    ['Retreat', '', ''],
    ['Travel', '', ''],
    ['Active', '', ''],
    ['Released', '', ''],
    ['PendingReincarnatedZhengWei', '', ''],
    ['Deceased', '', ''],
    ['Pending', '', ''],
    ['Applied', '', ''],
    ['sect.territory_reconcile', '', ''],
    ['sect.rebellion_sweep', '', ''],
    ['annual.adventure_realm', '', ''],
    ['annual.secret_realm', '', ''],
    ['annual.secret_realm_training', '', ''],
    ['annual.quanbing', '', ''],
    ['annual.yinsi', '', ''],
    ['annual.lecture', '', ''],
    ['annual.sect_task', '', ''],
    ['annual.craft_retention', '', ''],
    ['annual.governance', '', ''],
    ['annual.sect_war', '', ''],
    ['annual.family_support', '', ''],
    ['annual.world_detection', '', ''],
    ['annual.world_snapshot_maintenance', '', ''],
    ['annual.century_annals', '', ''],
    ['annual.codex', '', ''],
    ['annual.native_magic_ritual_guard', '', ''],
    ['annual.longshu_building_recovery', '', ''],
    ['annual.high_realm_army_exclusion', '', ''],
    ['annual.three_book_chronicle', '', ''],
    ['annual.world_event_catalog', '', ''],
    ['annual.dao_lineage_maintenance', '', ''],
    ['annual.rule_invariant_audit', '', ''],
    ['annual.guzun_maintenance', '', ''],
  ],
  qiyuan: [
    ['ManaRegen', '单位每月自然恢复的 mana', ''],
    ['SpiritRegen', '单位每月自然恢复的精神力', ''],
    ['MaxVigor', '骑士的斗气上限（突破资源）', ''],
    ['KnightEvasion', '骑士的闪避几率（自定义 stat；WorldBox 无原生闪避数值）', ''],
    ['HealthRegen', '单位每次生命恢复结算能够恢复的生命值', ''],
    ['IronArmor', '抵抗金属性伤害的护甲', ''],
    ['WoodArmor', '抵抗木属性伤害的护甲', ''],
    ['WaterArmor', '抵抗水属性伤害的护甲', ''],
    ['FireArmor', '抵抗火属性伤害的护甲', ''],
    ['EarthArmor', '抵抗土属性伤害的护甲', ''],
    ['NegArmor', '抵抗阴属性伤害的护甲', ''],
    ['PosArmor', '抵抗阳属性伤害的护甲', ''],
    ['EntropyArmor', '抵抗混沌属性伤害的护甲', ''],
    ['IronMaster', '提高金属性攻击效果的掌握属性', ''],
    ['WoodMaster', '提高木属性攻击效果的掌握属性', ''],
    ['WaterMaster', '提高水属性攻击效果的掌握属性', ''],
    ['FireMaster', '提高火属性攻击效果的掌握属性', ''],
    ['EarthMaster', '提高土属性攻击效果的掌握属性', ''],
    ['NegMaster', '提高阴属性攻击效果的掌握属性', ''],
    ['PosMaster', '提高阳属性攻击效果的掌握属性', ''],
    ['EntropyMaster', '提高混沌属性攻击效果的掌握属性', ''],
    ['MaxSoul', '单位能够容纳的最大魂量', ''],
    ['MaxQiyun', '单位能够容纳的最大气运', ''],
    ['DivineSense', '单位用于控制法器及计算分念容量的神识', ''],
    ['sect_recruit_requires_master_introduction', '标记宗门招募必须由师父引荐的统计标签', ''],
    ['sect_allow_disciple_organize_scripture', '标记宗门允许弟子参与整理藏经阁的统计标签', ''],
    ['RecruitRangeModifier', '宗门招募距离相对基础值的倍率修正', ''],
    ['RecruitMaxLevelBonus', '宗门可招募境界相对宗主境界上限的平铺加成', ''],
    ['RecruitRealmScoreModifier', '境界因素在宗门招募评分中的权重倍率修正', ''],
    ['MasterWillingnessThresholdModifier', '师父接纳弟子所需意愿门槛的倍率修正', ''],
    ['MasterApprenticeCapacityModifier', '宗门成员收徒容量的倍率修正', ''],
    ['TeachingGainModifier', '宗门教学行为产生收益的倍率修正', ''],
    ['LectureMaxAudienceBonus', '单次宗门讲法最大听众数量的平铺加成', ''],
    ['PersonnelRealmScoreModifier', '境界在宗门人事评分中的权重倍率修正', ''],
    ['PersonnelTenureScoreModifier', '入宗资历在宗门人事评分中的权重倍率修正', ''],
    ['PersonnelContributionScoreModifier', '宗门贡献在人事评分中的权重倍率修正', ''],
    ['PromotionScoreThresholdModifier', '成员晋升所需人事评分门槛的倍率修正', ''],
    ['DeaconSlotModifier', '执事职位数量的倍率修正', ''],
    ['ElderSlotModifier', '长老职位数量的倍率修正', ''],
    ['DeaconThresholdModifier', '晋升执事所需评分门槛的倍率修正', ''],
  ],
  zidingyi: [
    ['invincible', '', ''],
    ['inmny.custommodt001_custom.metamorph.origin_asset', '', ''],
    ['inmny.custommodt001_custom.metamorph.origin_subspecies', '', ''],
    ['inmny.custommodt001_custom.metamorph.expire', '', ''],
    ['inmny.custommodt001_custom', '', ''],
    ['inmny.custommodt001_custom.actor_history', '', ''],
    ['inmny.custommodt001_custom.enhance_level', '', ''],
    ['inmny.custommodt001_custom.enhance_exp', '', ''],
    ['inmny.custommodt001_custom.enhance_config', '', ''],
    ['inmny.custommodt001_custom.enhance_yearly_exp', '', ''],
    ['inmny.custommodt001_custom.enhance_kill_exp', '', ''],
    ['__all__', '', ''],
    ['__vanilla__', '', ''],
    ['inmny.custommodt001_custom.skill.', '', ''],
    ['inmny.custommodt001.skill.', '', ''],
    ['inmny.custommodt001.', '', ''],
    ['_summoned', '', ''],
    ['inmny.custommodt001_custom.summoned_obj_owner', '', ''],
    ['inmny.custommodt001_custom.assigned_system', '', ''],
    ['father_id', '', ''],
    ['mother_id', '', ''],
    ['level', '', ''],
    ['_cp_level_v10', '', ''],
    ['_cp_v10', '', ''],
    ['last_cultisys_update', '', ''],
    ['deathbound', '', ''],
    ['mortal_tongue', '', ''],
    ['initial_name', '', ''],
    ['inmny.custommodt001.wudao_exp', '', ''],
    ['inmny.custommodt001.wudao_level', '', ''],
    ['inmny.custommodt001.talent', '', ''],
    ['king_diplomacy', '', ''],
    ['lifespan', '', ''],
    ['CitySurrender', '', '配置分组：WarRule；类型：SWITCH；默认：True'],
    ['InheritSystemFromParents', '', '配置分组：WarRule；类型：SWITCH；默认：False'],
    ['TurbulentWorld', '', '配置分组：WarRule；类型：SWITCH；默认：False'],
    ['NoDurabilityLoss', '', '配置分组：WeaponRule；类型：SWITCH；默认：True'],
    ['BreakthroughHistory', '', '配置分组：ActorHistory；类型：SWITCH；默认：True'],
  ],
  zhutian: [
    ['wanzu_unit_ratio', '比例型属性的 Unit 标记。与 WanZuStatTable 中的标注一致', ''],
    ['wanzu_unit_percent_cap', '百分点型且有 100 上限 —— 物御 / 法御。同样不能 ×100', ''],
    ['stunned', '眩晕状态的资产 id。原版硬编码字符串，这里集中一处', ''],
    ['_nosave', '还没进入任何世界时用的目录名', ''],
    ['zhutianshenzuo.ct.temp.', '临时词条的到期时刻前缀。见 GetTempUntil 说明为何不与技能型共用', ''],
    ['zhutianshenzuo.ct.ver', '逐单位状态版本：授予/撤销/升级/技能开关时 ++，使该单位缓存失效', ''],
    ['zhutianshenzuo.tj.cur', '当前境界串：daoTuId=realmId 逗号分隔。空 = 未入任何境界', ''],
    ['zhutianshenzuo.tj.ver', '逐单位状态版本。境界每变必 ++，是加成缓存的失效依据之一', ''],
    ['zhutianshenzuo.tj.manual', '玩家手动加入的道途 id（逗号分隔）', ''],
    ['zhutianshenzuo.tj.lastYear', '系统年锚点。首次见到该单位时无条件写回', ''],
    ['zhutianshenzuo.tj.name.base', '基名快照（不含任何道途后缀）', ''],
    ['zhutianshenzuo.tj.name.mark', '上次由本系统写入 actor.data.name 的确切串。外部改名探测器', ''],
    ['zhutianshenzuo.tj.name.rev', '应用后缀时的 KEY_VER 值。**脏值守卫**，见 RefreshNameSuffix', ''],
    ['.off', '停用后缀。接在 .json 之后，于是停用文件不会被扫描命中', ''],
    ['zhutianshenzuo.tj.bolt', '已落雷数', ''],
    ['zhutianshenzuo.tj.total', '总雷数快照(渡劫开始时复制定义,防定义中途被改)', ''],
    ['zhutianshenzuo.tj.lastBolt', '渡劫开始时的世界时间(用于读档容错:跨长暂停自动补雷)', ''],
    ['zhutianshenzuo.tj.passed.', '「通过此天劫」的 bool 键前缀。后接天劫 id,例如 zhutianshenzuo.tj.passed.thunder_1', ''],
    ['zhutianshenzuo.wanzu.', '所有本系统持久化键的公共前缀', ''],
    ['yuanmai_layer', 'GodPower id，同时是 UI 按钮的 name 与本地化键前缀', ''],
    ['zhutianshenzuo.ct.dropDone', '幂等守卫：dieAndDestroy 链可能多次回调走 die()，与 karma/exp 各自独立', ''],
    ['zhutianshenzuo.tick.life_lock', '逐单位的上次锁定时刻。见 ActorTickGate 说明为何不能用全局静态', ''],
    ['zhutianshenzuo.ct.birthDone', '出生发放幂等守卫。与 WanZuGrantSystem 各用一个键，互不干扰', ''],
    ['zhutianshenzuo.ct.rolled.', '「这条已经摇过了」的前缀，后接词条 Id', ''],
    ['zhutianshenzuo.ct.kills', '累计击杀数，由 CiTiaoCombatPatches 递增', ''],
    ['zhutianshenzuo.tick.acquire', '逐单位的上次检查时刻。见 ActorTickGate 说明为何不能用全局静态', ''],
    ['zhutianshenzuo.tick.job_exp', '逐单位的上次检查时刻。见 ActorTickGate 说明为何不能用全局静态', ''],
    ['zhutianshenzuo.ct.wasFighting', '上次轮询时该单位是否在交战 —— 脱战边沿检测用', ''],
    ['zhutianshenzuo.tick.skill_check', '逐单位的上次检查时刻。见 ActorTickGate 说明为何不能用全局静态', ''],
    ['zhutianshenzuo.tick.ct_cost', '逐单位的上次结算时刻。见 ActorTickGate 说明为何不能用全局静态', ''],
    ['zhutianshenzuo.tick.daotu', '逐单位的上次检查时刻。见 ActorTickGate 说明为何不能用全局静态', ''],
    ['zhutianshenzuo.shidai.granted', '幂等标记：两条出生路径可能叠加，且 Harmony 不保证只触发一次', ''],
    ['zhutianshenzuo.tick.tianjie', '逐单位的节流键(落雷)。ActorTickGate 的索引值(无单位语义)', ''],
    ['zhutianshenzuo.tick.energy_regen', '逐单位的上次回复时刻。见 ActorTickGate 说明为何不能用全局静态', ''],
    ['zhutianshenzuo.release.next', '下次可放出的时间戳。逐单位存 actor.data，随存档走', ''],
    ['zhutianshenzuo.tick.growth', '逐单位的上次检查时刻。见 ActorTickGate 说明为何不能用全局静态', ''],
    ['zhutianshenzuo.tick.life_regen', '逐单位的上次回复时刻。见 ActorTickGate 说明为何不能用全局静态', ''],
    ['zhutianshenzuo.tick.lifespan', '逐单位的上次检查时刻。见 ActorTickGate 说明为何不能用全局静态', ''],
    ['zhutianshenzuo.wanzu.granted', '幂等标记：两条出生路径可能叠加，且 Harmony 补丁不保证只触发一次', ''],
    ['WanXiangLife', '', ''],
  ],
  zhanshen: [
    ['fallen_strong', '强势堕落者专属图标：被铁链束缚的破碎红刃', ''],
    ['fallen_weak', '低端堕落者专属图标：锈蚀衰败的断刃', ''],
    ['zhe_rank', '斩神榜窗口按钮图标', ''],
    ['zhe_grant', '神墟授予窗口按钮图标', ''],
    ['zhe_settings', '设置窗口按钮图标', ''],
    ['zhanshenlu.fallen_strong', '强势堕落者：疯狂值越过阈值，自行堕落', ''],
    ['zhanshenlu.fallen_weak', '低端堕落者：被堕落国度裹挟转化，国度覆灭即可恢复', ''],
    ['zhanshenlu.purger', '斩堕者：斩杀过堕落者后获得', ''],
    ['zhanshenlu.mystery', '畸变体：野生生物（非智慧生物）的修行特质，与斩神者境界一一对应到人类天花板', ''],
    ['zhanshenlu.mystery_power', '畸变体的凶焰值（相当于斩神者的精神力）', ''],
    ['zhanshenlu.jinwu_holder', '禁物持有者：身上带着一件禁物', ''],
    ['zhanshenlu.jinwu_id', '所持禁物的 id', ''],
    ['zhanshenlu.ageless_granted', '原版「不朽」（不老）特质是不是由本模组因王墟不朽而挂上的', ''],
    ['zhanshenlu.night_watch', '组织：守夜人', ''],
    ['zhanshenlu.watch_traitor', '叛出守夜人（堕落被除名）者永不再收', ''],
    ['zhanshenlu.watch_post_year', '写在城市数据上：最近一次有守夜人驻扎的年份', ''],
    ['zhanshenlu.watch_commander', '世界级存档：守夜人总司令的单位 id', ''],
    ['zhanshenlu.watch_squad_counter', '世界级存档：守夜人小队编号计数器', ''],
    ['zhanshenlu.watch_join_year', '守夜人成员：入队年份、职阶、小队编号、小队名', ''],
    ['zhanshenlu.watch_squads', '写在城市数据上：驻扎本城的小队编号（逗号分隔）', ''],
    ['zhanshenlu.fallen_slain', '斩杀过多少名堕落者', ''],
    ['zhanshenlu.madness_year', '疯狂值上次结算到的年份，用于按年自然消退', ''],
    ['zhanshenlu.old_name', '写在国家数据上：沦陷前的原国名', ''],
    ['zhanshenlu.madness', '旧日疯狂值', '0~100'],
    ['zhanshenlu.madness_stage', '上次结算到的疯狂阶段，用于识别跨阶段的那一刻', ''],
    ['zhanshenlu.deed_year', '上一次建功之年，用于神明青睐/失望判定', ''],
    ['zhanshenlu.godslayer', '斩杀过多少位神墟代理人', ''],
    ['zhanshenlu.oldone_survived', '自旧日疯狂中生还的次数', ''],
    ['zhanshenlu.forsaken', '曾被神明弃绝（叛离），计入堕落', ''],
    ['zhanshenlu.art_cd', '上次施展神术的时刻', ''],
    ['zhanshenlu.discourse_year', '上次论道之年', ''],
    ['zhanshenlu.grave.entries', '世界级存档：疯神墓地（已故堕落者名录）', ''],
    ['zhanshenlu.guardian_id', '写在城市数据上：该城镇守者的单位 id', ''],
    ['zhanshenlu.authority', '旧版的通用权柄', ''],
    ['jinse_liuli', '琉璃赤子心', ''],
    ['jinse_shengyue', '圣约', ''],
    ['jinse_baiwuchang', '白无常', ''],
    ['jinse_heiwuchang', '黑无常', ''],
    ['jinse_zhipei', '支配皇帝', ''],
    ['jinse_taxinyou', '他心游', ''],
  ],
  zhetian: [
    ['Dodge', '闪避率', ''],
    ['Accuracy', '命中率', ''],
    ['Resist', '', ''],
    ['attackRange', '', ''],
    ['Warrior', '', ''],
    ['Pattern', '', ''],
    ['RefinerMaterial', '', ''],
    ['TrueGang', '', ''],
    ['TrueGangTrueDamageMultiplier', '', ''],
    ['TrueGangHealMultiplier', '', ''],
    ['TrueGangDamageReductionMultiplier', '', ''],
    ['wushu.warriorNum', '', ''],
    ['wushu.trueGangNum', '', ''],
    ['strings.S.lifespan', '', ''],
    ['wushu.trueGangTrueDamageMultiplier', '', ''],
    ['wushu.trueGangHealMultiplier', '', ''],
    ['wushu.trueGangDamageReductionMultiplier', '', ''],
    ['wushu.patternNum', '', ''],
    ['wushu.warrior_level_cache', '', ''],
    ['wushu.formation_level_cache', '', ''],
    ['wushu.true_gang_limit_cache', '', ''],
    ['wushu.pattern_limit_cache', '', ''],
    ['wushu.last_trait_check', '', ''],
    ['zhetian.emperor_path.last_age', '', ''],
    ['zhetian.emperor_path.challenge_done', '', ''],
    ['zhetian.emperor_path.intent', '', ''],
    ['zhetian.emperor_path.intent_year', '', ''],
    ['claim_mandate', '', ''],
    ['self_dao', '', ''],
    ['zhetian.emperor_path.mandate_shadow_trial_last_year', '', ''],
    ['zhetian.emperor_path.mandate_shadow_trial_failure_count', '', ''],
    ['zhetian.emperor_path.mandate_shadow_trial_passed', '', ''],
    ['zhetian.emperor_path.life_count', '', ''],
    ['zhetian.emperor_path.alternative_checked', '', ''],
    ['zhetian.emperor_path.alternative_last_attempt_year', '', ''],
    ['zhetian.emperor_path.alternative_failure_count', '', ''],
    ['zhetian.emperor_path.proof_initialized', '', ''],
    ['zhetian.emperor_path.fall_announced', '', ''],
    ['zhetian.emperor_path.self_sever_initialized', '', ''],
    ['zhetian.emperor_path.proof_suppressed_age', '', ''],
  ],
  guimi: [
    ['Dodge', '闪避率', ''],
    ['misc_madness', '失控日志，不使用 lotm 分组（频率高，不进入历史标签）', ''],
    ['_ws_fate_branch_proc', '表示下次攻击×5', ''],
    ['canxiang.possession_seq', '单次生效', ''],
    ['Accuracy', '命中率', ''],
    ['damage', '每次微增，积少成多', ''],
    ['lotm_authority_bar_', '', ''],
    ['lotm_authority_bar_rule', '', ''],
    ['lotm_authority_bar_truth', '', ''],
    ['lotm_authority_bar_existence', '', ''],
    ['lotm_authority_bar_pollution', '', ''],
    ['lotm_authority_bar_situation', '', ''],
    ['lotm_authority_bar_position', '', ''],
    ['lotm_authority_bar_attack_cd', '', ''],
    ['lotm_authority_bar_receive_cd', '', ''],
    ['lotm_authority_bar_extreme_cd', '', ''],
    ['lotm_authority_bar_last_return', '', ''],
    ['authority_veil_broken', '', ''],
    ['lotm_duel_convergence_erosion', '', ''],
    ['Healback', '', ''],
    ['held_by_defender', '', ''],
    ['controlled_by_attacker', '', ''],
    ['blocked', '', ''],
    ['unavailable', '', ''],
    ['ended', '', ''],
    ['Resist', '', ''],
    ['ArmorPenPercent', '', ''],
    ['Vampire', '', ''],
    ['command', '', ''],
    ['organization', '', ''],
    ['lotm_star_state', '', ''],
    ['lotm_state_faith_last_challenge_year', '', ''],
    ['lotm_state_faith_last_challenge_faith', '', ''],
    ['lotm_state_faith_stabilized_until_year', '', ''],
    ['lotm_state_faith_stabilized_faith', '', ''],
    ['lotm_state_faith_suppressed_faith', '', ''],
    ['lotm_heresy_rise_until_year', '', ''],
    ['lotm_heresy_rise_faith', '', ''],
    ['lotm_heresy_rise_power', '', ''],
    ['lotm_orthodoxy_purge_until_year', '', ''],
  ],
  longzu: [
    ['dragon_shadow', '黑王固定暗影黑龙', ''],
    ['longzu.armor', '装备的防具 id', ''],
    ['longzu.trinket', '装备的饰品 id', ''],
    ['longzu.consumable', '携带的消耗品 id', ''],
    ['longzu.itemGrantCd', '授予冷却（世界时间）', ''],
    ['longzu.potionCd', '药剂服用冷却（世界时间）', ''],
    ['__ok__', '故意 value≠key，使 getText 探针可靠区分「缺失/已注册」', ''],
    ['longzu.talentPts', '未分配天赋点', ''],
    ['longzu.talentTrickle', '上次缓增的世界时间', ''],
    ['LongZu_Group_Blood', '血统', ''],
    ['LongZu_Group_Rank', '龙位', ''],
    ['LongZu_Group_Word', '言灵', ''],
    ['LongZu_Group_Faction', '阵营', ''],
    ['LongZu_Rank_Kin', '龙裔 1~3', '1~3'],
    ['LongZu_Rank_Lord', '龙侯 4~6', '4~6'],
    ['LongZu_Rank_Sovereign', '君主 7~8', '7~8'],
    ['LongZu_Rank_King', '龙王 9', ''],
    ['LongZu_Fac_Cassel', '卡塞尔学院', ''],
    ['LongZu_Fac_Snake', '蛇岐八家', ''],
    ['LongZu_Fac_Dragon', '龙族', ''],
    ['LongZu_DragonRage', '龙化失控', ''],
    ['longzu.blood', '血统等级 0~6（0=凡人, 1=E, 2=D, 3=C, 4=B, 5=A, 6=S）', '0~6'],
    ['longzu.purity', '血统纯度 0~100', 'float'],
    ['longzu.rank', '龙位 0~9', '0=无, 1~3龙裔, 4~6龙侯, 7~8君主, 9龙王'],
    ['longzu.throne', '君主席位 0~6（0=无席位，见 Sovereign.ThroneNames）', '0~6'],
    ['longzu.faction', '阵营 0=中立 1=卡塞尔学院 2=蛇岐八家 3=龙族', ''],
    ['longzu.rage', '龙化失控标记 0/1', ''],
    ['longzu.dragonOverlay', '真龙贴图层已挂载标志 0/1（v1.2.1 真模型视觉接入）', ''],
    ['longzu.sanity', '理智值 0~100（归零触发失控）', '0~100'],
    ['longzu.rageYears', '当前失控剩余年数（倒计时）', ''],
    ['longzu.rageCd', '失控结束后冷却剩余年数', ''],
    ['longzu.maxhp', '由本 MOD 接管的血量上限', ''],
    ['longzu.kills', '屠龙 / 击杀计数', ''],
    ['longzu.words', '已解锁言灵数量（缓存，便于面板显示）', ''],
    ['longzu.weapon', '持有的七宗罪 / 名刀 id（字符串）', ''],
    ['longzu.wbase', '凡人屠龙者未持刀时的基础攻击（幂等重算用）', ''],
    ['longzu.init', '是否已初始化血统 0/1', ''],
    ['longzu.autofav', '收藏标记是否由本 MOD 自动加的 0/1（避免误清玩家手动收藏）', ''],
    ['longzu.buffUntil', '增益（攻击/攻速）到期时间', ''],
    ['longzu.buffTier', '增益等级（禁咒/一等/…）', ''],
  ],
  wuji: [
    ['Dodge', '闪避率', ''],
    ['wushu.sectFounderIdx', '创立者标记：角色是否是某宗门创立者（存宗门在 All 中的索引）', ''],
    ['wushu.sectAppointedLeaderIdx', '被指定掌门标记：玩家手动指定的掌门（存宗门在 All 中的索引；-1=未指定）', ''],
    ['wushu.sectFoundedYear', '创立者标记：创立年份', ''],
    ['wushu.sectDeathSettled', '死亡结算标记：防止 Actor.die 多次调用导致声望扣减/掌门更替播报重复执行', ''],
    ['wushu.sectHallOf', '大殿建筑归属标记：值 = 宗门索引（SectRegistry.All 下标）', ''],
    ['wushu.sectHallX', '创立者身上持久化的大殿坐标键', ''],
    ['warrior_sect_hall', '大殿建筑 id（克隆 library_human 的装饰性建筑，不参与城邦生产）', ''],
    ['Accuracy', '命中率', ''],
    ['Resist', '', ''],
    ['Warrior', '', ''],
    ['Pattern', '', ''],
    ['Fortune', '', ''],
    ['TrueGang', '', ''],
    ['TrueGangTrueDamageMultiplier', '', ''],
    ['TrueGangHealMultiplier', '', ''],
    ['TrueGangDamageReductionMultiplier', '', ''],
    ['wushu.warriorNum', '', ''],
    ['wushu.trueGangNum', '', ''],
    ['strings.S.lifespan', '', ''],
    ['wushu.trueGangTrueDamageMultiplier', '', ''],
    ['wushu.trueGangHealMultiplier', '', ''],
    ['wushu.trueGangDamageReductionMultiplier', '', ''],
    ['wushu.patternNum', '', ''],
    ['wushu.duboFortune', '', ''],
    ['wushu.warrior_level_cache', '', ''],
    ['wushu.formation_level_cache', '', ''],
    ['wushu.true_gang_limit_cache', '', ''],
    ['wushu.pattern_limit_cache', '', ''],
    ['wushu.last_trait_check', '', ''],
    ['wushu.formation_last_trait_check', '', ''],
    ['WJ_FamilyTreeButton', '', ''],
    ['WJ_SectButton', '', ''],
    ['wushu.sectHallY', '', ''],
    ['wushu.demonDeathRecorded', '', ''],
    ['wushu.houseDeathRecorded', '', ''],
    ['wushu.duboFortuneLastYear', '', ''],
    ['wushu.duboDeathNotified', '', ''],
    ['library_human', '', ''],
    ['buildings', '', ''],
  ],
  xuanmen: [
    ['xuanpin.OriginalName', '清除错误的原始名字', ''],
    ['xuanpin.LastNameRealm', '强制重新生成', ''],
    ['XianLing', '', ''],
    ['LingLian', '', ''],
    ['ZhenWo', '', ''],
    ['HunSu', '', ''],
    ['ChaoKe', '', ''],
    ['XianYunMax', '', ''],
    ['LingYunMax', '', ''],
    ['ZhenYunMax', '', ''],
    ['HunYunMax', '', ''],
    ['ChaoYunMax', '', ''],
    ['XianYun', '', ''],
    ['LingYun', '', ''],
    ['ZhenYun', '', ''],
    ['HunYun', '', ''],
    ['ChaoYun', '', ''],
    ['LingQiConversionRate', '', ''],
    ['QingLingQiConsume', '', ''],
    ['ZhuoLingQiConsume', '', ''],
    ['HunDunLingQiConsume', '', ''],
    ['WuXiBonus', '', ''],
    ['WuYunBonus', '', ''],
    ['xuanpin.city_traits.', '', ''],
    ['xuanpin.XianYunNum', '', ''],
    ['xuanpin.LingYunNum', '', ''],
    ['xuanpin.ZhenYunNum', '', ''],
    ['xuanpin.HunYunNum', '', ''],
    ['xuanpin.ChaoYunNum', '', ''],
    ['xuanpin.XiuWeiNum', '', ''],
    ['xuanpin.TuRealmLevel', '', ''],
    ['xuanpin.DaoJiPotential', '', ''],
    ['xuanpin.DaoJiFinalized', '', ''],
    ['xuanpin.LingHuiAffinity', '', ''],
    ['xuanpin.LingHuiFinalized', '', ''],
    ['xuanpin.LingHuiTraits', '', ''],
    ['xuanpin.Title', '', ''],
    ['xuanpin.TitleRealm', '', ''],
    ['xuanpin.QiHaiGrade', '', ''],
    ['xuanpin.QiHaiAcquireAge', '', ''],
  ],
  shengwuxue: [
    ['bio_grave_window', '', ''],
    ['bio_grave_raw', '', ''],
    ['list_favorite_units', '', ''],
    ['cthulhu_brain_1', '', ''],
    ['cthulhu_brain_2', '', ''],
    ['cthulhu_minion', '', ''],
    ['cthulhu_minion_2', '', ''],
    ['golden_brain', '', ''],
    ['bio_lifespan_override', '', ''],
    ['intelligence', '', ''],
    ['lifespan', '', ''],
    ['health', '', ''],
    ['birth_rate', '', ''],
    ['speed', '', ''],
    ['damage', '', ''],
    ['armor', '', ''],
    ['critical_chance', '', ''],
    ['attack_speed', '', ''],
    ['diplomacy', '', ''],
    ['warfare', '', ''],
    ['stewardship', '', ''],
    ['菜单缩放', '', '配置分组：窗口设置；类型：SLIDER；范围：0.5~2.0；默认：0.5'],
    ['面板宽度', '', '配置分组：窗口设置；类型：INT_SLIDER；范围：160~400；默认：160'],
    ['器官面板加宽倍数', '', '配置分组：窗口设置；类型：SLIDER；范围：1.0~2.5；默认：2.0'],
    ['启用动物器官', '', '配置分组：功能开关；类型：SWITCH；默认：False'],
    ['点击探针', '', '配置分组：功能开关；类型：SWITCH；默认：False'],
    ['裸体立绘', '', '配置分组：功能开关；类型：SWITCH；默认：False'],
    ['器官磨损', '', '配置分组：功能开关；类型：SWITCH；默认：True'],
    ['矮人贴图', '', '配置分组：功能开关；类型：SWITCH；默认：True'],
    ['人类贴图', '', '配置分组：功能开关；类型：SWITCH；默认：True'],
    ['隐藏服装', '', '配置分组：功能开关；类型：SWITCH；默认：False'],
    ['屏幕调试提示', '', '配置分组：诊断设置；类型：SWITCH；默认：False'],
  ],
  kuajie: [
    ['cw_cn_seq', '写在 Kingdom.data 上的当前序列号', ''],
    ['cw_cn_base', '写在 Kingdom.data 上的「树基名」——同一棵树所有节点共享的原归属国国名', ''],
    ['cw_cross_nation', '写在 Kingdom.data 上的键', ''],
    ['cwb_remote_marks', '国王 / 军旗 / 大船 / 剑盾', ''],
    ['cwb_remote_marks_small', '城主 / 小船', ''],
    ['cwb_remote_battles', '战斗地点', ''],
    ['cwb_remote_warline', '战线箭头', ''],
    ['sea_tile', '世界贴片（PNG / JPG）', ''],
    ['sea_pixels', '远端实景 · 细节层稀疏点表（v1.11.3，高频小消息）', ''],
    ['sea_live_req', '请求对方回传一张实景截图', ''],
    ['sea_focus', '请对方把镜头对准它自己的世界（有人要切过来看）', ''],
    ['sea_marks', '世界铭牌快照（国名 / 旗帜 / 城市 / 军团）', ''],
    ['sea_moving', '远端实景 · 会动的地图标记位置表（v1.11.4，高频小消息）', ''],
    ['peer_list', '对等体名录交换（gossip）：一个好码拉进全网', ''],
    ['net_update', '房间内广播：某人要改自己的候选端点（换网络 / 重新映射端口后）', ''],
    ['culture_spread', '', ''],
    ['CWB_AUTOSTART', '', ''],
    ['CWB_PARENT', '', ''],
    ['cw_legion', '', ''],
    ['cw_legion_world', '', ''],
    ['cw_legion_war', '', ''],
    ['cw_traveler', '', ''],
    ['cw_traveler_world', '', ''],
    ['cw_traveler_name', '', ''],
    ['cw_faction_origin', '', ''],
    ['crossworld_bridge', '', ''],
    ['cw_bridge_tab', '', ''],
    ['snapshot_request', '', ''],
    ['war_declare', '', ''],
    ['war_accept', '', ''],
    ['war_reject', '', ''],
    ['war_status', '', ''],
    ['war_peace', '', ''],
    ['war_resolved', '', ''],
    ['travel_send', '', ''],
    ['travel_ack', '', ''],
    ['faction_send', '', ''],
    ['faction_ack', '', ''],
    ['normal', '', ''],
    ['cw_declare_war', '', ''],
  ],
  xihuan: [
    ['guild.members', '会长直属队员', ''],
    ['guild.points', '公会积分', ''],
    ['mentorship.teacher_id', '老师ID', ''],
    ['mentorship.student_ids', '学生ID列表', ''],
    ['mentorship.last_recruit_year', '上次收徒年份', ''],
    ['mentorship.teaching_book_name', '教学书本名称', ''],
    ['mentorship.teaching_book_target_deduce', '教学书本目标推演次数', ''],
    ['__scroll_attack__', '攻击卷轴冷却键', ''],
    ['__scroll_healing__', '治疗卷轴冷却键', ''],
    ['wushu.DeterminationNum', '意志力', ''],
    ['wushu.DefydeathNum', '跨越死亡', ''],
    ['wushu.BattleIntentNum', '战意', ''],
    ['wushu.PaladinToughNum', '坚韧', ''],
    ['wushu.PhilosophersStoneNum', '贤者之石', ''],
    ['wushu.AngerNum', '血气', ''],
    ['wushu.DodgeEvadeNum', '闪避', ''],
    ['wushu.hitthetargetNum', '命中', ''],
    ['wushu.MagicApplicationNum', '魔力法应用', ''],
    ['wushu.MeditationExperienceNum', '冥想法经验', ''],
    ['wushu.MeditationInsightNum', '冥想法悟性', ''],
    ['wushu.MeditationTierNum', '冥想法悟性层数', ''],
    ['wushu.SimulationsNum', '推演', ''],
    ['wushu.DeductiveAttributeNum', '推演属性', ''],
    ['wushu.DeductiveRequirementNum', '推演需求', ''],
    ['wushu.ExperienceBonusNum', '经验加成', ''],
    ['wushu.MeditationDamageNum', '冥想法伤害', ''],
    ['wushu.MeditationMagicalEnergyNum', '冥想魔力', ''],
    ['wushu.MagicShield', '护盾', ''],
    ['wushu.FixedPhysicalDamage', '固定物伤', ''],
    ['wushu.FixedMagicalDamage', '固定法伤', ''],
    ['wushu.Restorehealth', '回血', ''],
    ['wushu.MagicReply', '魔力回复', ''],
    ['wushu.MagicDamage', '法伤', ''],
    ['wushu.MagicResistance', '法抗', ''],
    ['wushu.PhysicalDamage', '物伤', ''],
    ['wushu.PhysicalDefense', '物抗', ''],
    ['wushu.LegendaryStatus', '传奇', ''],
    ['wushu.SpiritFallNum', '灵堕', ''],
    ['wushu.ManaUnitNum', '魔力单位', ''],
    ['wushu.EphemeralMarks', '须臾之刻', ''],
  ],
  fanren: [
    ['fanren.breakthrough_heal', '突破回血标记（由常驻刷新器结算）', ''],
    ['fanren.danfang.made', '修士 data 位图键前缀（fanren.danfang.made0..3，每 slot 32 位，条目平铺序号 = 卷×每卷条目数 + 卷内下标）', ''],
    ['fanren.herb', '灵草存量（炼丹材料）', ''],
    ['fanren.peiyin_until', '培婴丹：元婴出窍加成截止时间', ''],
    ['fanren.peiyin_bonus', '培婴丹：实际出窍加成百分点', ''],
    ['fanren.wudao_until_year', '悟道丹：修炼加速截止年龄', ''],
    ['fanren.wudao_mult', '悟道丹：实际修炼倍率', ''],
    ['fanren.ningxin_until', '宁心丹：免疫异常状态截止时间', ''],
    ['fanren.quti_stacks', '淬体丹：永久生命加成层数', ''],
    ['fanren.fabao_category', 'int 0-9；-1/缺省=未定型（旧档）', '0-9'],
    ['fanren.fabao_name', '词库名（空=旧档掌天瓶/青竹蜂云剑）', ''],
    ['fanren.fabao_equip_src', '炼化原料装备 ID', ''],
    ['fanren.fenshen.count', '当前分身数量', ''],
    ['fanren.fenshen_cd_until', '凝聚冷却截止时间', ''],
    ['fanren.fenshen_saves', '累计救主次数（编年史）', ''],
    ['fanren.fenshen_saved', '本次死亡已救主标记（一次性，供 NascentSoulSystem 联动拦截）', ''],
    ['fanren.zhenfa_name', '阵法师：护身大阵名（随机绑定一次）', ''],
    ['fanren.lingjiu_name', '灵厨：最近酿成灵酒名', ''],
    ['fanren.fu_names', '制符师：近期炼制符名（去重累积）', ''],
    ['fanren.lingzhi_names', '灵植夫：曾辨识灵植名（去重累积）', ''],
    ['fanren.spirit_stones', '旧版单一 int 存量键（仅迁移用）', ''],
    ['fanren.zongmen.id', '成员/掌门：所属宗门 ID', ''],
    ['fanren.zongmen.name', '掌门：宗门名', ''],
    ['fanren.zongmen.master', '掌门：标记 1', ''],
    ['fanren.zongmen.founded', '掌门：成立世界年', ''],
    ['fanren.zongmen.found_try', '修士：最近一次开宗尝试年份', ''],
    ['fanren.zongmen.founder', '掌门：创建者（开宗祖师）名，继承时保留', ''],
    ['fanren.zongmen.gen', '掌门：宗主代数（创建者=1）', ''],
    ['fanren.zongmen.city_id', '掌门：绑定城镇 data.id（0 = 山野宗门）', ''],
    ['fanren.zongmen.city_name', '掌门：绑定城镇名', ''],
    ['fanren.zongmen.grade', '掌门：宗门品阶 0凡宗/1灵宗/2圣宗/3仙宗', ''],
    ['fanren.zongmen.assets.stones', '掌门：仓库灵石存量', ''],
    ['fanren.zongmen.assets.herb', '掌门：仓库灵草存量', ''],
    ['fanren.zongmen.assets.pills', '掌门：仓库丹药存量', ''],
    ['fanren.zongmen.lingmai.tier', '掌门：绑定灵脉品阶（-1 未绑定）', ''],
    ['fanren.zongmen.lingmai.x', '掌门：绑定灵脉坐标 X', ''],
    ['fanren.zongmen.lingmai.y', '掌门：绑定灵脉坐标 Y', ''],
    ['fanren.zongmen.lingmai.dist', '掌门：绑定距离快照（格，仅 UI 展示）', ''],
    ['fanren_status_peiyin', '', ''],
    ['fanren_status_wudao', '', ''],
  ],
  wangshengshu: [
    ['actor_history_archive', '', ''],
    ['actor_history_archive_title', '', ''],
    ['button_actor_history_archive', '', ''],
    ['button_actor_history_archive_description', '', ''],
    ['actor_history', '', ''],
    ['actor_history_title', '', ''],
    ['actor_history_button_tip', '', ''],
    ['actor_history_button_tip_desc', '', ''],
    ['actor_history_world_key', '', ''],
    ['reft_archive.db', '', ''],
    ['reft_reincarnation', '', ''],
    ['reft.possess.active', '', ''],
    ['reft.possess.ghost', '', ''],
    ['reft.possess.host', '', ''],
    ['reft.possess.traits', '', ''],
    ['reft.possess.mult', '', ''],
    ['reft.possess.stage', '', ''],
    ['reft.possess.year', '', ''],
    ['reft.possess.exposure', '', ''],
    ['reft.cfg.reincarnation', '', ''],
    ['reft.cfg.lonely_soul', '', ''],
    ['reft.cfg.possession', '', ''],
    ['reft.', '', ''],
    ['reft.reincarnation_delay', '', ''],
    ['reft.trait_inherit', '', ''],
    ['reft.lonely_threshold', '', ''],
    ['reft.lonely_lifespan', '', ''],
    ['reft.lonely_never_fade', '', ''],
    ['reft.preserved_traits', '', ''],
    ['reft.madness_trait', '', ''],
    ['reft.kill_reenter', '', ''],
    ['reft.possess_enabled', '', ''],
    ['reft.possess_chance', '', ''],
    ['reft.possess_min_stage', '', ''],
    ['reft.possess_radius', '', ''],
    ['wushu.warriorNum', '', ''],
    ['wushu.trueGangNum', '', ''],
    ['wushu.patternNum', '', ''],
    ['wushu.warrior_level_cache', '', ''],
    ['wushu.formation_level_cache', '', ''],
  ],
  xianni: [ // 该模组无 .cs 源码（只有 XianniMod.dll），属性库/数据键抽不到；以下为 default_config.json 里的配置项
    ['xn_config_enable_log', '', '配置分组：xn_config_basic；类型：SWITCH；默认：True'],
    ['xn_config_enable_animation', '', '配置分组：xn_config_basic；类型：SWITCH；默认：True'],
    ['xn_config_enable_titles', '', '配置分组：xn_config_basic；类型：SWITCH；默认：True'],
    ['xn_config_enable_title_generation', '', '配置分组：xn_config_basic；类型：SWITCH；默认：True'],
    ['xn_config_enable_broadcast_display', '', '配置分组：xn_config_basic；类型：SWITCH；默认：True'],
    ['xn_config_enable_broadcast_console_log', '', '配置分组：xn_config_basic；类型：SWITCH；默认：False'],
    ['xn_config_enable_mc_select_sfx', '', '配置分组：xn_config_basic；类型：SWITCH；默认：True'],
    ['xn_config_unit_search_keyword', '', '配置分组：xn_config_basic；类型：TEXT'],
    ['xn_config_skin_tone_color', '', '配置分组：xn_config_basic；类型：INT_SLIDER；范围：0~15；默认：0'],
    ['xn_config_city_aura_max', '', '配置分组：xn_config_cultivation；类型：TEXT'],
    ['xn_config_city_aura_refresh_years', '', '配置分组：xn_config_cultivation；类型：TEXT'],
    ['xn_config_auto_fav_realm_gate', '', '配置分组：xn_config_cultivation；类型：TEXT'],
    ['xn_config_broadcast_realm_gate', '', '配置分组：xn_config_cultivation；类型：INT_SLIDER；范围：0~13；默认：1'],
    ['xn_config_tianyun_years', '', '配置分组：xn_config_cultivation；类型：TEXT'],
    ['xn_config_enable_tianyunzi_spawn', '', '配置分组：xn_config_cultivation；类型：SWITCH；默认：True'],
    ['xn_config_enable_xiuzhenguo_suppress', '', '配置分组：xn_config_cultivation；类型：SWITCH；默认：True'],
    ['xn_config_enable_ancient_beast_level_limit', '', '配置分组：xn_config_cultivation；类型：SWITCH；默认：True'],
    ['xn_config_enable_xiuzhenguo_aura_limit', '', '配置分组：xn_config_cultivation；类型：SWITCH；默认：True'],
    ['xn_config_ancient_beast_multiplier', '', '配置分组：xn_config_cultivation；类型：INT_SLIDER；范围：1~10000；默认：1'],
    ['xn_config_disable_condense', '', '配置分组：xn_config_cultivation；类型：SWITCH；默认：False'],
    ['xn_config_ambition_add_value', '', '配置分组：xn_config_gameplay；类型：TEXT'],
    ['xn_config_enable_auto_join_army', '', '配置分组：xn_config_gameplay；类型：SWITCH；默认：False'],
    ['xn_config_enable_building_protection', '', '配置分组：xn_config_gameplay；类型：SWITCH；默认：False'],
    ['xn_config_dashou_behavior', '', '配置分组：xn_config_gameplay；类型：TEXT'],
    ['xn_config_enable_demonic_hunt', '', '配置分组：xn_config_gameplay；类型：SWITCH；默认：True'],
    ['xn_config_enable_bloodline_awaken', '', '配置分组：xn_config_gameplay；类型：SWITCH；默认：True'],
    ['xn_config_enable_mentorship', '', '配置分组：xn_config_gameplay；类型：SWITCH；默认：True'],
    ['xn_config_enable_tatian_suppression', '', '配置分组：xn_config_gameplay；类型：SWITCH；默认：True'],
    ['xn_config_enable_tournament_death_match', '', '配置分组：xn_config_gameplay；类型：SWITCH；默认：True'],
    ['xn_config_enable_bomb_skills', '', '配置分组：xn_config_gameplay；类型：SWITCH；默认：True'],
    ['xn_config_enable_ai_voice', '', '配置分组：xn_config_ai；类型：SWITCH；默认：False'],
    ['xn_config_enable_deepseek_textgen', '', '配置分组：xn_config_ai；类型：SWITCH；默认：False'],
    ['xn_config_custom_ai_api_key', '', '配置分组：xn_config_ai；类型：TEXT'],
    ['xn_config_custom_ai_url', '', '配置分组：xn_config_ai；类型：TEXT'],
    ['xn_config_custom_ai_model', '', '配置分组：xn_config_ai；类型：TEXT'],
    ['xn_config_enable_auto_gc', '', '配置分组：xn_config_performance；类型：SWITCH；默认：False'],
    ['xn_config_auto_gc_threshold_mb', '', '配置分组：xn_config_performance；类型：TEXT'],
    ['xn_config_enable_xianni_law', '', '配置分组：xn_config_advanced；类型：SWITCH；默认：True'],
    ['xn_config_enable_death_law', '', '配置分组：xn_config_advanced；类型：SWITCH；默认：False'],
  ],
  guzhenren: [
    ['gz_gift_rain', '自定义雨滴掉落物 id（贴图复用原版 delta_rain 雨滴，落地行为自定义）', ''],
    ['guzhenren_faction_history', '势力事件专属历史栏目组（历史窗口独立页签）', ''],
    ['guzhenren_faction_events', '势力事件日志资源（写入“势力”栏目）', ''],
    ['guzhenren_realm_history', '秘境事件专属历史栏目组（历史窗口独立页签，专门播报秘境）', ''],
    ['guzhenren_realm_events', '秘境事件日志资源（写入「秘境」栏目）', ''],
    ['guzhenren.dependency_owner', '从仙窍诞生的蛊仙隶属于某个蛊仙，存储主人 ActorId', ''],
    ['guzhenren.dependency_owner_name', '从属主人姓名快照：主人陨落后仍可显示姓名', ''],
    ['guzhenren.auto_favorite', '自动收藏标记：记录该收藏由蛊真人自动收藏写入，便于清理误收/失效收藏', ''],
    ['guzhenren.daohen_realm_formed', '死亡结算 ReturnRemainingDaoHenToWorld 见到此标记则跳过回池，杜绝死后道痕双倍反馈', ''],
    ['guzhenren.death_by_realm_explore', '尸体已有 death_settled 去重，标记无需清理', ''],
    ['Dodge', '', ''],
    ['Resist', '', ''],
    ['ArmorPenPercent', '', ''],
    ['guzhenren.stuck_target', '', ''],
    ['guzhenren.stuck_start', '', ''],
    ['guzhenren.stuck_sep_cd', '', ''],
    ['guzhenren.stuck_atk_frame', '', ''],
    ['guzhenren.stuck_atk_target', '', ''],
    ['yuan_shi', '', ''],
    ['xian_yuanshi', '', ''],
    ['mortal_worm', '', ''],
    ['xian_worm', '', ''],
    ['kill_move', '', ''],
    ['mortal_material', '', ''],
    ['immortal_material', '', ''],
    ['xian_recipe', '', ''],
    ['tong_tian_gu', '', ''],
    ['shen_nian_gu', '', ''],
    ['bao_guang_xian_gu', '', ''],
    ['guzhenren.beast', '', ''],
    ['guzhenren.beast_gift_worms', '', ''],
    ['guzhenren.beast_wave_id', '', ''],
    ['guzhenren.beast_wave_king', '', ''],
    ['guzhenren.beast_wave_combat_prepared', '', ''],
    ['guzhenren.dao_pool.', '', ''],
    ['GZ_LifeEraser', '', ''],
    ['GZ_GiftRain', '', ''],
    ['fx_slash', '', ''],
    ['guzhenren.inner_tick_year', '', ''],
    ['guzhenren.inner_fake', '', ''],
  ],
  dengshen: [
    ['ds_deep_awakening', '深度觉醒', ''],
    ['ds_status_out_of_control', '能力失控', ''],
    ['ds_void_corruption', '虚空侵蚀', ''],
    ['ds_foundation_damaged', '能力根基受损', ''],
    ['ds_era_dominator', '真神纪元主宰加成', ''],
    ['ds_status_gene_mutation', '4阶专属：基因突变者', ''],
    ['ds_status_breakthrough_momentum', '破境之势：挑战上位时的临时战力爆发状态', ''],
    ['ds_qi', '异能能量（原"灵气"，key不变）', ''],
    ['ds_anchor', '道心锚点心神锚点（key不变）', ''],
    ['ds_sanctuary', '圣域激活状态（key不变）', ''],
    ['ds_in_divine', '神域中（key不变）', ''],
    ['ds_fallen', '永久堕落（key不变）', ''],
    ['ds_enlight', '深度觉醒经验（原"悟道经验"，key不变）', ''],
    ['ds_enlight_dur', '深度觉醒状态持续时间（年）', ''],
    ['ds_mastery', '能力掌控度 0~100（替代印记系统，符合现代异能体系）', '0~100'],
    ['ds_ge_cache', '基因能量缓存（年度Tick时计算，战斗时直接读取，减轻性能负担）', ''],
    ['ds_link_dmg', '基因连锁伤害加成缓存（年度Tick时计算）', ''],
    ['ds_link_def', '基因连锁防御加成缓存', ''],
    ['ds_link_hp', '基因连锁生命加成缓存', ''],
    ['ds_gene_unlocked', '已解锁基因节点ID（逗号分隔）', ''],
    ['ds_gene_kills', '战斗击杀数', ''],
    ['ds_gene_defense', '战斗承受攻击数', ''],
    ['ds_gene_uses', '异能使用次数', ''],
    ['ds_gene_continuous', '连续修炼年数', ''],
    ['ds_gene_low_corr', '低失控持续年数', ''],
    ['ds_gene_domain_days', '场域维持天数', ''],
    ['ds_gene_deep_enlight', '深度觉醒次数', ''],
    ['ds_stat_cult_years', '修炼总时长（年）', ''],
    ['ds_stat_break_cnt', '突破次数', ''],
    ['ds_stat_max_turb', '历史失控峰值', ''],
    ['ds_stat_kills', '总击杀数', ''],
    ['ds_stat_ability_kills', '异能击杀数', ''],
    ['ds_stat_highest_tier', '历史最高境界', ''],
    ['ds_stat_awaken_year', '觉醒年份', ''],
    ['ds_stat_total_energy', '累计获得能量', ''],
    ['ds_stat_disasters', '经历灾变次数', ''],
    ['gene_expr_', '基因表达层级key前缀', ''],
    ['ds_elem_unlocked', '已解锁基因ID（逗号分隔）', ''],
    ['ds_elem_attempted', '已尝试获得的基因ID（逗号分隔，任务只能完成一次）', ''],
    ['ds_combos_active', '已激活组合ID（逗号分隔）', ''],
  ],
};
